### ISSUE TITLE
Melkille myös AD-tunnuksilla

### ISSUE THREAD

**Issue by juhapekkamoilanen** [tkt-lapio/tkt-lapio.github.io#16]
Kuulema melkille ym. pääsee nykyään AD-tunnuksilla, voisi siis päivittää tämän sivun tietoja: https://github.com/tkt-lapio/tkt-lapio.github.io/blob/master/_posts/1969-28-12-osaston-jarjestelmat.markdown?

**Comment by irenenikk** [comment]
Korjattu! Kiitos tiedosta :)
