### ISSUE TITLE
Päivitys default-haaran nimestä

### ISSUE THREAD

**Issue by jobatabs** [tkt-lapio/tkt-lapio.github.io#54]
Hei,

ohjeistuksessa voisi mainita, että nykyään git luo defaulttina uuden haaran nimellä `main`, ei `master`.

Halutessaan myös tämän repon haaran nimen voisi vaihtaa.

Lisätietoa:
https://github.com/github/renaming
https://sfconservancy.org/news/2020/jun/23/gitbranchname/
https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main

**Comment by dogamak** [comment]
Muutin viittaukset master-haaraan maininnoiksi main-haarasta ja lisäsin tällaisen boxin. Cubblissa ei kuitenkaan taida vielä olla niin uusi gitin versio, että siinä oletusnimi olisi vielä vaihtunut.

![2022-01-20-194028_765x184_scrot](https://user-images.githubusercontent.com/2016731/150393052-959a90be-ec26-4a7b-8cb6-6518cf1c0b85.png)

**Comment by dogamak** [comment]
Voisihan tuossa tietysti vielä linkata johonkin artikkeliin asiasta.
